import os
import streamlit as st
from dotenv import load_dotenv
from google import genai
from google.genai import types

# 1. Load the API key from your local .env file securely
load_dotenv()

# 2. Initialize the client (it automatically looks for GEMINI_API_KEY inside your loaded environment)
client = genai.Client()

# 2. Set up the web page header layout
st.set_page_config(page_title="AI Movie Vibe Recommender", layout="centered")
st.title("🎬 Contextual Movie Recommender")
st.subheader("Find the perfect film based on your exact mood or theme")

# 3. Define the core instructions and your 200 movie list
SYSTEM_INSTRUCTION = """
You are a brilliant, conversational movie recommendation engine. 
You will be provided with a catalog of movies including their titles, ratings, and overviews. 
Your job is to analyze the user's request and recommend the top 3 closest matches from the catalog.

For each recommendation, format the output nicely using Markdown like this:
### 1. Movie Title (Rating: 7.5)
**Why watch it:** 2-sentence explanation matching their exact mood request.

[MOVIE CATALOG]
Title: Toy Story | Rating: 7.7 | Overview: Led by Woody, Andy's toys live happily...
Title: Jumanji | Rating: 6.9 | Overview: When siblings Judy and Peter discover an enchanted board game...
Title: Grumpier Old Men | Rating: 6.5 | Overview: A family wedding reignites the ancient feud between next-door neighbors and fishing buddies John and Max. Meanwhile, a sultry Italian divorcée opens a restaurant at the local bait shop, alarming the locals who worry she'll scare the fish away. But she's less interested in seafood than she is in cooking up a hot time with Max.
Title: Waiting to Exhale | Rating: 6.1 | Overview: Cheated on, mistreated and stepped on, the women are holding their breath, waiting for the elusive "good man" to break a string of less-than-stellar lovers. Friends and confidants Vannah, Bernie, Glo and Robin talk it all out, determined to find a better way to breathe.
Title: Father of the Bride Part II | Rating: 5.7 | Overview: Just when George Banks has recovered from his daughter's wedding, he receives the news that she's pregnant ... and that George's wife, Nina, is expecting too. He was planning on selling their home, but that's a plan that -- like George -- will have to change with the arrival of both a grandchild and a kid of his own.
Title: Heat | Rating: 7.7 | Overview: Obsessive master thief, Neil McCauley leads a top-notch crew on various insane heists throughout Los Angeles while a mentally unstable detective, Vincent Hanna pursues him without rest. Each man recognizes and respects the ability and the dedication of the other even though they are aware their cat-and-mouse game may end in violence.
Title: Sabrina | Rating: 6.2 | Overview: An ugly duckling having undergone a remarkable change, still harbors feelings for her crush: a carefree playboy, but not before his business-focused brother has something to say about it.
Title: Tom and Huck | Rating: 5.4 | Overview: A mischievous young boy, Tom Sawyer, witnesses a murder by the deadly Injun Joe. Tom becomes friends with Huckleberry Finn, a boy with no future and no family. Tom has to choose between honoring a friendship or honoring an oath because the town alcoholic is accused of the murder. Tom and Huck go through several adventures trying to retrieve evidence.
Title: Sudden Death | Rating: 5.5 | Overview: International action superstar Jean Claude Van Damme teams with Powers Boothe in a Tension-packed, suspense thriller, set against the back-drop of a Stanley Cup game.Van Damme portrays a father whose daughter is suddenly taken during a championship hockey game. With the captors demanding a billion dollars by game's end, Van Damme frantically sets a plan in motion to rescue his daughter and abort an impending explosion before the final buzzer...
Title: GoldenEye | Rating: 6.6 | Overview: James Bond must unmask the mysterious head of the Janus Syndicate and prevent the leader from utilizing the GoldenEye weapons system to inflict devastating revenge on Britain.
Title: The American President | Rating: 6.5 | Overview: Widowed U.S. president Andrew Shepherd, one of the world's most powerful men, can have anything he wants -- and what he covets most is Sydney Ellen Wade, a Washington lobbyist. But Shepherd's attempts at courting her spark wild rumors and decimate his approval ratings.
Title: Dracula: Dead and Loving It | Rating: 5.7 | Overview: When a lawyer shows up at the vampire's doorstep, he falls prey to his charms and joins him in his search for fresh blood. Enter Dr. van Helsing, who may be the only one able to vanquish the count.
Title: Balto | Rating: 7.1 | Overview: An outcast half-wolf risks his life to prevent a deadly epidemic from ravaging Nome, Alaska.
Title: Nixon | Rating: 7.1 | Overview: An all-star cast powers this epic look at American President Richard M. Nixon, a man carrying the fate of the world on his shoulders while battling the self-destructive demands within. Spanning his troubled boyhood in California to the shocking Watergate scandal that would end his presidency.
Title: Cutthroat Island | Rating: 5.7 | Overview: Morgan Adams and her slave, William Shaw, are on a quest to recover the three portions of a treasure map. Unfortunately, the final portion is held by her murderous uncle, Dawg. Her crew is skeptical of her leadership abilities, so she must complete her quest before they mutiny against her. This is made yet more difficult by the efforts of the British crown to end her pirate raids.
Title: Casino | Rating: 7.8 | Overview: The life of the gambling paradise – Las Vegas – and its dark mafia underbelly.
Title: Sense and Sensibility | Rating: 7.2 | Overview: Rich Mr. Dashwood dies, leaving his second wife and her daughters poor by the rules of inheritance. Two daughters are the titular opposites.
Title: Four Rooms | Rating: 6.5 | Overview: It's Ted the Bellhop's first night on the job...and the hotel's very unusual guests are about to place him in some outrageous predicaments. It seems that this evening's room service is serving up one unbelievable happening after another.
Title: Ace Ventura: When Nature Calls | Rating: 6.1 | Overview: Summoned from an ashram in Tibet, Ace finds himself on a perilous journey into the jungles of Africa to find Shikaka, the missing sacred animal of the friendly Wachati tribe. He must accomplish this before the wedding of the Wachati's Princess to the prince of the warrior Wachootoos. If Ace fails, the result will be a vicious tribal war.
Title: Money Train | Rating: 5.4 | Overview: A vengeful New York transit cop decides to steal a trainload of subway fares; his foster brother, a fellow cop, tries to protect him.
Title: Get Shorty | Rating: 6.4 | Overview: Chili Palmer is a Miami mobster who gets sent by his boss, the psychopathic "Bones" Barboni, to collect a bad debt from Harry Zimm, a Hollywood producer who specializes in cheesy horror films. When Chili meets Harry's leading lady, the romantic sparks fly. After pitching his own life story as a movie idea, Chili learns that being a mobster and being a Hollywood producer really aren't all that different.
Title: Copycat | Rating: 6.5 | Overview: An agoraphobic psychologist and a female detective must work together to take down a serial killer who copies serial killers from the past.
Title: Assassins | Rating: 6 | Overview: Assassin Robert Rath arrives at a funeral to kill a prominent mobster, only to witness a rival hired gun complete the job for him -- with grisly results. Horrified by the murder of innocent bystanders, Rath decides to take one last job and then return to civilian life. But finding his way out of the world of contract killing grows ever more dangerous as Rath falls for his female target and becomes a marked man himself.
Title: Powder | Rating: 6.3 | Overview: Harassed by classmates who won't accept his shocking appearance, a shy young man known as "Powder" struggles to fit in. But the cruel taunts stop when Powder displays a mysterious power that allows him to do incredible things. This phenomenon changes the lives of all those around him in ways they never could have imagined.
Title: Leaving Las Vegas | Rating: 7.1 | Overview: Ben Sanderson, an alcoholic Hollywood screenwriter who lost everything because of his drinking, arrives in Las Vegas to drink himself to death. There, he meets and forms an uneasy friendship and non-interference pact with prostitute Sera.
Title: Othello | Rating: 7 | Overview: The evil Iago pretends to be friend of Othello in order to manipulate him to serve his own end in the film version of this Shakespeare classic.
Title: Now and Then | Rating: 6.6 | Overview: Waxing nostalgic about the bittersweet passage from childhood to puberty in this tender coming-of-age tale, four childhood girlfriends -- Teeny, Chrissy, Samantha and Roberta -- recall the magical summer of 1970. During their walk down memory lane, they reconcile experiences with boys, secrets, bullies and more.
Title: Persuasion | Rating: 7.4 | Overview: This film adaptation of Jane Austen's last novel follows Anne Elliot, the daughter of a financially troubled aristocratic family, who is persuaded to break her engagement to Frederick Wentworth, a young sea captain of meager means. Years later, money troubles force Anne's father to rent out the family estate to Admiral Croft, and Anne is again thrown into company with Frederick -- who is now rich, successful and perhaps still in love with Anne.
Title: La Cité des Enfants Perdus | Rating: 7.6 | Overview: A scientist in a surrealist society kidnaps children to steal their dreams, hoping that they slow his aging process.
Title: 摇啊摇，摇到外婆桥 | Rating: 6.5 | Overview: A provincial boy related to a Shanghai crime family is recruited by his uncle into cosmopolitan Shanghai in the 1930s to be a servant to a ganglord's mistress.
Title: Dangerous Minds | Rating: 6.4 | Overview: Former Marine Louanne Johnson lands a gig teaching in a pilot program for bright but underachieving teens at a notorious inner-city high school. After having a terrible first day, she decides she must throw decorum to the wind. When Johnson returns to the classroom, she does so armed with a no-nonsense attitude informed by her military training and a fearless determination to better the lives of her students -- no matter what the cost.
Title: Twelve Monkeys | Rating: 7.4 | Overview: In the year 2035, convict James Cole reluctantly volunteers to be sent back in time to discover the origin of a deadly virus that wiped out nearly all of the earth's population and forced the survivors into underground communities. But when Cole is mistakenly sent to 1990 instead of 1996, he's arrested and locked up in a mental hospital. There he meets psychiatrist Dr. Kathryn Railly, and patient Jeffrey Goines, the son of a famous virus expert, who may hold the key to the mysterious rogue group, the Army of the 12 Monkeys, thought to be responsible for unleashing the killer disease.
Title: Guillaumet, les ailes du courage | Rating: 6.8 | Overview: 
Title: Babe | Rating: 6 | Overview: Babe is a little pig who doesn't quite know his place in the world. With a bunch of odd friends, like Ferdinand the duck who thinks he is a rooster and Fly the dog he calls mom, Babe realizes that he has the makings to become the greatest sheep pig of all time, and Farmer Hogget knows it. With the help of the sheep dogs Babe learns that a pig can be anything that he wants to be.
Title: Carrington | Rating: 6.4 | Overview: The story of the relationship between painter Dora Carrington and author Lytton Strachey in a World War One England of cottages and countryside. Although platonic due to Strachey's homosexuality, the relationship was nevertheless a deep and complicated one. When Carrington did develop a more physical relationship with soldier Ralph Partridge, Strachey was able to welcome him as a friend, although Partridge remained somewhat uneasy, not so much with Strachey's lifestyle and sexual orientation as with the fact that he was a conscientious objector.
Title: Dead Man Walking | Rating: 7.3 | Overview: A justice drama based on a true story about a man on death row who in his last days forms a strong relationship with a nun who teaches him forgiveness and gives him spirituality as she accompanies him to his execution. Susan Sarandon won an Oscar for best female actress for her convincing portrayal of Sister Helen Prejean.
Title: Across the Sea of Time | Rating: 3.5 | Overview: A young Russian boy, Thomas Minton, travels to New York as a passenger on a Russian freighter. Close to Ellis Island he gets off and thus starts his journey to America the same way as all immigrants in former times. Thomas is searching for the family of one of his ancestors, who had emigrated decades ago, but once sent a letter home together with a sample of his new profession: 3D-Photography. The boy follows his relative's traces by counter-checking the old 3D-Photographs of New York (using an antique viewer) with the same places and how they look today. This way, the audience gets to see the Big Apple in former times as well as today.
Title: It Takes Two | Rating: 6.1 | Overview: Identical 9-year-olds from very different backgrounds: orphaned Amanda and wealthy Alyssa meet at summer camp and decide to switch places -- and play matchmaker between Alyssa's dad, Roger, and the kind social worker who cares for Amanda.
Title: Clueless | Rating: 6.9 | Overview: Shallow, rich and socially successful Cher is at the top of her Beverly Hills high school's pecking scale. Seeing herself as a matchmaker, Cher first coaxes two teachers into dating each other. Emboldened by her success, she decides to give hopelessly klutzy new student Tai a makeover. When Tai becomes more popular than she is, Cher realizes that her disapproving ex-stepbrother was right about how misguided she was -- and falls for him.
Title: Cry, the Beloved Country | Rating: 6.7 | Overview: A South-African preacher goes to search for his wayward son who has committed a crime in the big city.
Title: Richard III | Rating: 6.9 | Overview: Shakespeare's Play transplanted into a 1930s setting.
Title: Dead Presidents | Rating: 6.6 | Overview: Depicts a heist of old bills, retired from circulation and destined by the government to be "money to burn". However, more broadly, it addresses the issues of Black Americans' involvement in the Vietnam War and their subsequent disillusionment with progress in social issues and civil rights back home in the United States, during the 1960s.
Title: Restoration | Rating: 6.3 | Overview: An aspiring young physician, Robert Merivel found himself in the service of King Charles II and saves the life of someone close to the King. Merivel joins the King's court and lives the high life provided to someone of his position. Merivel is ordered to marry his King's mistress in order to divert the queens suspicions. He is given one order by the king and that is not to fall in love. The situation worsens when Merivel finds himself in love with his new wife. Eventually, the King finds out and relieves Merivel of his position and wealth. His fall from grace leaves Merivel where he first started. And through his travels and reunions with an old friend, he rediscovers his love for true medicine and what it really means to be a physician.
Title: Mortal Kombat | Rating: 5.4 | Overview: For nine generations an evil sorcerer has been victorious in hand-to-hand battle against his mortal enemies. If he wins a tenth Mortal Kombat tournament, desolation and evil will reign over the multiverse forever. To save Earth, three warriors must overcome seemingly insurmountable odds, their own inner demons, and superhuman foes in this action/adventure movie based on one of the most popular video games of all time.
Title: To Die For | Rating: 6.7 | Overview: Susan wants to work in television and will therefore do anything it takes, even if it means killing her husband. A very dark comedy from independent director Gus Van Sant with a brilliant Nicole Kidman in the leading role.
Title: How To Make An American Quilt | Rating: 6.5 | Overview: Soon-to-be-wed graduate student Finn Dodd develops cold feet when she suspects her fiancé is cheating on her. In order to clear her head, Finn visits her grandmother, Hy, and great aunt, Glady Joe Cleary, in Grasse, Calif. There, Finn learns that Hy and Glady Joe are members of a group of passionate quilters, and over the course of her visit she is regaled with tales of love and life by women who have collected rich experiences and much wisdom.
Title: Se7en | Rating: 8.1 | Overview: Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the "seven deadly sins" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer's mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.
Title: Pocahontas | Rating: 6.7 | Overview: History comes gloriously to life in Disney's epic animated tale about love and adventure in the New World. Pocahontas is a Native American woman whose father has arranged for her to marry her village's best warrior. But a vision tells her change is coming, and soon she comes face to face with it in the form of Capt. John Smith.
Title: When Night Is Falling | Rating: 5.9 | Overview: A prudish woman, working on tenure as a literacy professor at a large urban university, finds herself strangely attracted to a free-spirited, liberal woman whom works at a local carnival which comes to town.
Title: The Usual Suspects | Rating: 8.1 | Overview: Held in an L.A. interrogation room, Verbal Kint attempts to convince the feds that a mythic crime lord, Keyser Soze, not only exists, but was also responsible for drawing him and his four partners into a multi-million dollar heist that ended with an explosion in San Pedro harbor – leaving few survivors. Verbal lures his interrogators with an incredible story of the crime lord's almost supernatural prowess.
Title: Guardian Angel | Rating: 6.3 | Overview: Detective - turned - bodyguard Cynthia McKay (Cynthia Rothrock) is hired by a psychotic icy seductress, Nina Lindell (Lydie Denier), the same woman who killed Mckay's lover months earlier.  With vendetta in her heart McKay accompanies the flamboyantly playful womanizer through the glamourous world of the super-rich as his protector.  In a unique role reversal, it is the woman protecting the man from another woman, erupting into a deadly triangle of passion, suspense and action.
Title: Mighty Aphrodite | Rating: 6.7 | Overview: When Lenny and his wife, Amanda, adopt a baby, Lenny realizes that his son is a genius and becomes obsessed with finding the boy's biological mother in hopes that she will be brilliant too. But when he learns that Max's mother is Linda Ash, a kindhearted prostitute and porn star, Lenny is determined to reform her immoral lifestyle. A Greek chorus chimes in to relate the plot to Greek mythology in this quirky comedy.
Title: Lamerica | Rating: 7.7 | Overview: Fiore, an Italian conman, arrives in post Communist Albania with Gino, his young apprentice, to set up a shoe factory that will never open. The con requires a native Albanian, so they designate Spiro, an impoverished and confused former political prisoner as chairman of the board. When Fiore returns to Italy to get government funds for the project, Spiro unexpectedly disappears and Gino sets out on a journey to find him. The search leads him to discover Spiro's tragic personal history and witness Albanian poverty firsthand.
Title: The Big Green | Rating: 5.2 | Overview: In a depressed Texas town, British foreign exchange teacher Anna attempts to inject some life into her hopeless kids by introducing them to soccer. They're terrible at first, but Anna and her football-hero assistant whip them into shape. As they work overtime, the pair help kids build their self-esteem and also get involved in solving family squabbles.
Title: Georgia | Rating: 6.1 | Overview: Sadie looks up to her older sister Georgia, a successful folk singer who's happily married with children, but can't break out of the bar-band circuit and hit the big time she desperately covets. It's in part due to her attraction to drugs and booze, and also to her own unwise choice in men. Finally, though, Sadie's Achilles heel is a rough, unlovely voice very different than her sister's crowd-pleasing singing.
Title: Kids of the Round Table | Rating: 3 | Overview: Set in modern times, Alex finds King Arthur's sword Excalibur and must prove himself worthy of it.
Title: Home for the Holidays | Rating: 6.3 | Overview: After losing her job, making out with her soon to be ex-boss, and finding out that her daughter plans to spend Thanksgiving with her boyfriend, Claudia Larson has to face spending the holiday with her family. She wonders if she can survive their crazy antics.
Title: Il postino | Rating: 7.6 | Overview: Simple Italian postman learns to love poetry while delivering mail to a famous poet; he uses this to woo local beauty Beatrice.
Title: Le confessionnal | Rating: 6.5 | Overview: The year is 1952, in Quebec City. Rachel (16), unmarried and pregnant, works in the church. Filled with shame, she unburdens her guilt to a young priest, under the confidentiality of the confessional. In the present year of 1989, Pierre Lamontagne has returned to Quebec to attend his father's funeral. He meets up with his adopted brother, Marc, who has begun questioning his identity and has embarked on a quest for his roots that would lead them to the Quebec of the 1950s. Past and present converge in a complex web of intrigue where the answer to the mystery lies.
Title: The Indian in the Cupboard | Rating: 5.9 | Overview: A nine-year-old boy gets a plastic Indian and a cupboard for his birthday and finds himself involved in adventure when the Indian comes to life and befriends him.
Title: Eye for an Eye | Rating: 5.8 | Overview: It's fire and brimstone time as grieving mother Karen McCann takes justice into her own hands when a kangaroo court in Los Angeles fails to convict Robert Doob, the monster who raped and murdered her 17-year-old daughter.
Title: Mr. Holland's Opus | Rating: 6.9 | Overview: In 1965, passionate musician Glenn Holland takes a day job as a high school music teacher, convinced it's just a small obstacle on the road to his true calling: writing a historic opus. As the decades roll by with the composition unwritten but generations of students inspired through his teaching, Holland must redefine his life's purpose.
Title: Don't Be a Menace to South Central While Drinking Your Juice in the Hood | Rating: 6.2 | Overview: When Ashtray (Shawn Wayans) moves to South Central L.A. to live with his father (who appears to be the same age he is) and grandmother (who likes to talk tough and smoke reefer), he falls in with his gang-banging cousin Loc Dog (Marlon Wayans), who along with the requisite pistols and Uzi carries a thermo-nuclear warhead for self-defense. Will Ashtray be able to keep living the straight life?
Title: Two If by Sea | Rating: 4.5 | Overview: Frank O'Brien, a petty thief, and his 7-year-long girlfriend Roz want to put an end to their unsteady lifestyle and just do that last job, which involves stealing a valuable painting. Frank takes Roz to an island on the coast of New England, where he wants to sell the painting and also hopes that their sagging relationship will get a positive push back up. Not everything goes as planned.
Title: Bio-Dome | Rating: 4.4 | Overview: Bud and Doyle are two losers who are doing nothing with their lives. Both of their girlfriends are actively involved in saving the environment, but the two friends couldn't care less about saving the Earth. One day, when a group of scientists begin a mission to live inside a "Bio-Dome" for a year without outside contact, Bud and Doyle mistakenly become part of the project themselves.
Title: Lawnmower Man 2: Beyond Cyberspace | Rating: 2.8 | Overview: Jobe is resuscitated by Jonathan Walker. He wants Jobe to create a special computer chip that would connect all the computers in the world into one network, which Walker would control and use. But what Walker doesn't realize is a group of teenage hackers are on to him and out to stop his plan.
Title: Two Bits | Rating: 5.4 | Overview: It's a hot summer day in 1933 in South Philly, where 12-year old Gennaro lives with his widowed mom and his ailing grandpa, who sits outside holding tight to his last quarter, which he's promised to Gennaro and which Gennaro would like to have to buy a ticket to the plush new movie theater. But grandpa's not ready to pass on the quarter or pass on to his final reward: he has some unfinished business with a woman from his past, and he enlists Gennaro to act as his emissary.
Title: Gazon maudit | Rating: 6 | Overview: After learning of her husband's infidelities, a housewife invites an itinerant lesbian to move in with them. None of their lives will ever be the same again.
Title: Friday | Rating: 7 | Overview: Craig and Smokey are two guys in Los Angeles hanging out on their porch on a Friday afternoon, smoking and drinking, looking for something to do.
Title: From Dusk Till Dawn | Rating: 6.9 | Overview: Seth Gecko and his younger brother Richard are on the run after a bloody bank robbery in Texas. They escape across the border into Mexico and will be home-free the next morning, when they pay off the local kingpin. They just have to survive 'from dusk till dawn' at the rendezvous point, which turns out to be a Hell of a strip joint.
Title: Fair Game | Rating: 4.1 | Overview: Max Kirkpatrick is a cop who protects Kate McQuean, a civil law attorney, from a renegade KGB team out to terminate her
Title: Kicking and Screaming | Rating: 7 | Overview: After college graduation, Grover's girlfriend Jane tells him she's moving to Prague to study writing. Grover declines to accompany her, deciding instead to move in with several friends, all of whom can't quite work up the inertia to escape their university's pull. Nobody wants to make any big decisions that would radically alter his life, yet none of them wants to end up like Chet, the professional student who tends bar and is in his tenth year of university studies.
Title: Les misérables | Rating: 6.6 | Overview: In France during World War II, a poor and illiterate man, Henri Fortin (Jean-Paul Belmondo), is introduced to Victor Hugo's classic novel Les Misérables and begins to see parallels between the book and his own life.
Title: Bed of Roses | Rating: 5.1 | Overview: The seeds of love are planted when Lisa, a high-powered investment banker, receives flowers from a secret admirer. But when his fairy-tale fantasies clash with her workaholic ways, they soon find out that sometimes, it's harder than it seems for love to conquer all.
Title: Big Bully | Rating: 3.9 | Overview: A writer returns to his hometown where he faces the childhood nemesis whose life he ultimately ruined, only the bully wants to relive their painful past by torturing him once again.
Title: Screamers | Rating: 6.1 | Overview: (SIRIUS 6B, Year 2078) On a distant mining planet ravaged by a decade of war, scientists have created the perfect weapon: a blade-wielding, self-replicating race of killing devices known as Screamers designed for one purpose only -- to hunt down and destroy all enemy life forms.
Title: Nico Icon | Rating: 7.3 | Overview: A look into the many lives of Christa Päffgen, otherwise known as Nico; from cutie German mädchen to the first of the supermodels, to glamorous diva of the Velvet Underground, to cult item, junkie and hag. Many faces for the same woman, whom, you realize, just couldn't bring herself to care enough to live.
Title: The Crossing Guard | Rating: 6.1 | Overview: After his daughter died in a hit and run, Freddy Gale has waited six years for John Booth, the man responsible, to be released from prison. On the day of release, Gale visits Booth and announces that he will kill him in one week. Booth uses his time to try and make peace with himself and his entourage, and even finds romance. Gale, whose life is spiraling down because of his obsession towards Booth, will bring himself on the very edge of sanity. At he end of the week, both men will find themselves on a collision course with each other.
Title: The Juror | Rating: 5.5 | Overview: With his gangster boss on trial for murder, a mob thug known as "the Teacher" tells Annie Laird she must talk her fellow jurors into a not-guilty verdict, implying that he'll kill her son Oliver if she fails. She manages to do this, but, when it becomes clear that the mobsters might want to silence her for good, she sends Oliver abroad and tries to gather evidence of the plot against her, setting up a final showdown.
Title: بادکنک سفید | Rating: 7.5 | Overview: Several people try to take advantage of a little girl's innocence to hustle money her mom gave to her to buy a goldfish with.
Title: Things to Do in Denver When You're Dead | Rating: 6.7 | Overview: A mafia film in Tarantino style with a star-studded cast. Jimmy’s “The Saint” gangster career has finally ended. Yet now he finds him self doing favors for a wise godfather known as “The Man with the Plan.”
Title: Antonia | Rating: 7.2 | Overview: After World War II, Antonia and her daughter, Danielle, go back to their Dutch hometown, where Antonia's late mother has bestowed a small farm upon her. There, Antonia settles down and joins a tightly-knit but unusual community. Those around her include quirky friend Crooked Finger, would-be suitor Bas and, eventually for Antonia, a granddaughter and great-granddaughter who help create a strong family of empowered women.
Title: Once Upon a Time... When We Were Colored | Rating: 4.5 | Overview: This film relates the story of a tightly connected Afro-American community informally called Colored Town where the inhabitants live and depend on each other in a world where racist oppression is everywhere, as told by a boy called Cliff who spent his childhood there. Despite this, we see the life of the community in all its joys and sorrows, of those that live there while others decide to leave for a better life north. For those remaining, things come to a serious situation when one prominent businessman is being muscled out by a white competitor using racist intimidation. In response, the community must make the decision of whether to submit meekly like they always have, or finally fight for their rights.
Title: Last Summer in the Hamptons | Rating: 0 | Overview: Filmed entirely on location in East Hampton, Long Island, "Last Summer in the Hamptons" concerns a large theatrical family spending the last weekend of their summer together at the decades-old family retreat which economic circumstances have forced them to put on the market. Victoria Foyt plays a young Hollywood actress whose visit wreaks havoc on the stellar group of family and friends - led by matriarch Viveca Lindfors and made up of an extraordinary mix of prominent New York actors, directors, and playwrights. In the course of a very unusual weekend, comic as well as serious situations arise, and the family's secrets - of which there are many - begin to unravel.
Title: Angels and Insects | Rating: 6.3 | Overview: In Victorian England, wealthy patriarch Sir Harald Alabaster invites an impoverished biologist, William Adamson, into his home. There, William tries to continue his work, but is distracted by Alabaster's seductive daughter, Eugenia. William and Eugenia begin a torrid romance, but as the couple become closer, the young scientist begins to realize that dark, disturbing things are happening behind the closed doors of the Alabaster manor.
Title: White Squall | Rating: 6.3 | Overview: Teenage boys discover discipline and camaraderie on an ill-fated sailing voyage.
Title: Dunston Checks In | Rating: 5.1 | Overview: Hotel manager Robert Grant is forced by his boss to postpone his family vacation when a hotel critic checks in. Trouble is, the critic is really a villainous jewel thief with an orangutan assistant named Dunston. When Dunston gets loose and tries to escape a life of crime -- aided by Robert's sons -- havoc, hijinks and lots of laughs abound!
Title: Black Sheep | Rating: 6 | Overview: When dignified Albert Donnelly runs for Governor, his team moves to keep his slow-witted and klutzy younger brother, Mike, out of the eye of the media. To baby-sit Mike, the campaign assigns sarcastic Steve, who gets the experience of a lifetime when he tries to take Mike out of town during the election.
Title: Nick of Time | Rating: 6.1 | Overview: Gene Watson is a public accountant who arrives on a train at Union Station in Los Angeles, accompanied by his 6-year-old daughter Lynn. Because of his ordinary looks, he is approached by a pair of sinister people named Smith and Jones.
Title: The Journey of August King | Rating: 6.7 | Overview: The Journey of August King is a multi-dimensional drama about a North Carolina farmer in 1815. August King, a widower, is on his way home as he does every year after selling his produce and purchasing the stock and goods he will need to survive the winter. On his journey, he comes upon a run-away slave, a young woman about 19 and August King must decide to violate the law and help this slave to freedom or else leave her to be hunted down and, ultimately, returned to her slave owner.
Title: Mary Reilly | Rating: 5.7 | Overview: A housemaid falls in love with Dr. Jekyll and his darkly mysterious counterpart, Mr. Hyde.
Title: Vampire in Brooklyn | Rating: 4.5 | Overview: Maximillian, the lone survivor of a race of vampires, comes to Brooklyn in search of a way to live past the next full moon. His ticket to survival is Rita, a NYPD detective who doesn't know she's half vampire -- and Maximillian will do whatever's necessary to put her under his spell.
Title: Beautiful Girls | Rating: 6.6 | Overview: During a snowy winter in the small fictional town of Knight"s Ridge, Massachusetts, a group of lifelong buddies hang out, drink and struggle to connect with the women who affect their decisions, dreams and desires.
Title: Broken Arrow | Rating: 5.7 | Overview: When rogue stealth-fighter pilot Vic Deakins deliberately drops off the radar while on maneuvers, the Air Force ends up with two stolen nuclear warheads -- and Deakins's co-pilot, Riley Hale, is the military's only hope for getting them back. Traversing the deserted canyons of Utah, Hale teams with park ranger Terry Carmichael to put Deakins back in his box.
Title: A Midwinter's Tale | Rating: 7.5 | Overview: Out of work actor Joe volunteers to help try and save his sister's local church for the community by putting on a Christmas production of Hamlet, somewhat against the advice of his agent Margaretta. As the cast he assembles are still available even at Christmas and are prepared to do it on a 'profit sharing' basis (that is, they may not get paid anything) he cannot expect - and does not get - the cream of the cream. But although they all bring their own problems and foibles along, something bigger starts to emerge in the perhaps aptly named village of Hope.
Title: La Haine | Rating: 7.9 | Overview: Aimlessly whiling away their days in the concrete environs of their dead-end suburbia, Vinz, Hubert, and Said -- a Jew, African, and an Arab -- give human faces to France's immigrant populations, their bristling resentment at their social marginalization slowly simmering until it reaches a climactic boiling point. La Haine means Hate.
Title: Shopping | Rating: 5.6 | Overview: A dark, hip, urban story of a barren and anonymous city where the underclass' sport of choice is ram-raiding. An exciting game in which stolen cars are driven through shop windows to aid large-scale looting before the police arrive. For Tommy, it's a business, but for Billy and Jo, it's a labour of love. As the competition between Tommy and Billy grows more fierce, the stakes become higher and the "shopping" trips increasingly risky.
Title: Heidi Fleiss: Hollywood Madam | Rating: 6.8 | Overview: A documentary crew from the BBC arrives in L.A. intent on interviewing Heidi Fleiss, a year after her arrest for running a brothel but before her trial. Several months elapse before the interview, so the crew searches for anyone who'll talk about the young woman. Two people have a lot to say to the camera: a retired madam named Alex for whom Fleiss once worked and Fleiss's one-time boyfriend, Ivan Nagy, who introduced her to Alex. Alex and Nagy don't like each other, so the crew shuttles between them with "she said" and "he said." When they finally interview Fleiss, they spend their time reciting what Alex and Nagy have had to say and asking her reaction.
Title: City Hall | Rating: 6 | Overview: The accidental shooting of a boy in New York leads to an investigation by the Deputy Mayor, and unexpectedly far-reaching consequences.
Title: Bottle Rocket | Rating: 6.8 | Overview: Upon his release from a mental hospital following a nervous breakdown, the directionless Anthony joins his friend Dignan, who seems far less sane than the former. Dignan has hatched a hair-brained scheme for an as-yet-unspecified crime spree that somehow involves his former boss, the (supposedly) legendary Mr. Henry.
Title: Mr. Wrong | Rating: 3.3 | Overview: A single and lonely woman finds the seemingly perfect man to date, but soon regrets it when his deranged and possessive other personality emerges and worst still, she cannot convince anyone else of his Jekyll/Hyde true nature.
Title: Unforgettable | Rating: 5.3 | Overview: Ray Liotta stars as a medical examiner who has been acquitted for his wife's murder but many still question his innocence. Obsessed with finding his wife's killer, a possible solution presents itself in an experimental serum designed by a neurobiology Linda Fiorentino which has the ability to transfer memories from one person to another, but not without consequences. Liotta driven to solve the case injects himself with the serum, bringing him closer and closer to finding her killer but bringing him closer to death.
Title: Happy Gilmore | Rating: 6.5 | Overview: Failed hockey player-turned-golf whiz Happy Gilmore -- whose unconventional approach and antics on the grass courts the ire of rival Shooter McGavin -- is determined to win a PGA tournament so he can save his granny's house with the prize money. Meanwhile, an attractive tour publicist tries to soften Happy's image.
Title: The Bridges of Madison County | Rating: 7.3 | Overview: Photographer Robert Kincaid wanders into the life of housewife Francesca Johnson for four days in the 1960s.
Title: Keiner liebt mich | Rating: 5.1 | Overview: No overview found.
Title: Muppet Treasure Island | Rating: 6.5 | Overview: After telling the story of Flint's last journey to young Jim Hawkins, Billy Bones has a heart attack and dies just as Jim and his friends are attacked by pirates. The gang escapes into the town where they hire out a boat and crew to find the hidden treasure, which was revealed by Bones before he died. On their voyage across the seas, they soon find out that not everyone on board can be trusted.
Title: Catwalk | Rating: 7 | Overview: A documentary following Christy Turlington and other models during spring fashion week in Milan, Paris and New York.
Title: Headless Body in Topless Bar | Rating: 0 | Overview: An ex-con holds a group of people hostage in a topless bar.
Title: Braveheart | Rating: 7.7 | Overview: Enraged at the slaughter of Murron, his new bride and childhood love, Scottish warrior William Wallace slays a platoon of the local English lord's soldiers. This leads the village to revolt and, eventually, the entire country to rise up against English rule.
Title: Taxi Driver | Rating: 8.1 | Overview: A mentally unstable Vietnam War veteran works as a night-time taxi driver in New York City where the perceived decadence and sleaze feeds his urge for violent action, attempting to save a preadolescent prostitute in the process.
Title: 紅番區 | Rating: 6.5 | Overview: Keong comes from Hong Kong to visit New York for his uncle's wedding. His uncle runs a market in the Bronx and Keong offers to help out while Uncle is on his honeymoon. During his stay in the Bronx, Keong befriends a neighbor kid and beats up some neighborhood thugs who cause problems at the market. One of those petty thugs in the local gang stumbles into a criminal situation way over his head.
Title: Before and After | Rating: 5.8 | Overview: Two parents deal with the effects when their son is accused of murdering his girlfriend.
Title: Margaret's Museum | Rating: 7.5 | Overview: In a town where half the men die down the coalpit, Margaret MacNeil is quite happy being single in her small Cape Breton island town. Until she meets Neil Currie, a charming and sincere bagpipe-playing, Gaelic-speaking dishwasher. But no matter what you do, you can't avoid the spectre of the pit forever.
Title: Le Bonheur est dans le pré | Rating: 7 | Overview: Francis, the boss of a small plumbing supply company, is harassed by tax collectors, striking employees, and an impossible wife and daughter. His only joy is sharing lunch with his friend Gerard. Then a TV show called "where are you?" shows a woman from Gers who is searching for her husband who disappeared 28 years ago. The lost husband looks like an identical twin of Francis...
Title: Anne Frank Remembered | Rating: 7.3 | Overview: Using previously unreleased archival material in addition to contemporary interviews, this academy award-winning documentary tells the story of the Frank family and presents the first fully-rounded portrait of their brash and free-spirited daughter Anne, perhaps the world's most famous victim of the Holocaust. Written by Dawn M. Barclift
Title: The Young Poisoner's Handbook | Rating: 6.9 | Overview: A sinister tale of genius gone wrong, The Young Poisoner's Handbook chronicles a young man's descent into madness against the absurd backdrop of suburban English life. Hugh O'Conor plays Graham Young, a schoolboy from the London suburbs whose deadly obsession with toxic substances causes him to dabble in experimental murder.
Title: If Lucy Fell | Rating: 5.4 | Overview: Joe and Lucy are roommates and best friends. Lucy, whose love life is embarrassingly dull, convinces Joe, who is infatuated with a neighbor he's never met, that if they don't have stable romances within a month, they must jump off the Brooklyn Bridge.
Title: Steal Big Steal Little | Rating: 5.1 | Overview: Ruben and Robby are twin brothers, adopted by Mona, one of the wealthiest - and most eccentric - women in Santa Barbara. Ruben is devoted to Mona, but Robby is more devoted to her money. So when Mona leaves her fortune and estate to Ruben it starts a battle between brothers that soon leads to madness, mayhem, and even attempted murder. On Ruben's side is Lou Perilli an ex-Chicago cop and used car dealer who knows the law - and how to get around it. On Robby's side is ruthless businessman Reed Tyler, who is out to turn a swift profit on Mona's property. Walking a shifty line between them is Eddie Agopian, the family lawyer, who doesn't care which side wins as long as he's on the winner's side. But whether they're stealing big or stealing little, they're all stealing in this hilarious comedy about greed, power... and brotherly love.
Title: Race the Sun | Rating: 5.2 | Overview: A bunch of high school misfits in Hawaii, introduced by their new teacher, attend a science fair in which they draw up inspiration to build their own solar car and win a trip to compete in the 1990 World Solar Challenge in Australia.
Title: The Boys of St. Vincent | Rating: 7 | Overview: The true story of boys being sexually abused at their orphanage ran by a religious community in Newfoundland.
Title: Boomerang | Rating: 5.4 | Overview: Marcus is a successful advertising executive who woos and beds women almost at will. After a company merger he finds that his new boss, the ravishing Jacqueline, is treating him in exactly the same way. Completely traumatised by this, his work goes badly downhill.
Title: 重慶森林 | Rating: 7.9 | Overview: Every day, Cop 223 buys a can of pineapple with an expiration date of May 1, symbolizing the day he'll get over his lost love. He's also got his eye on a mysterious woman in a blond wig, oblivious of the fact she's a drug dealer. Cop 663 is distraught with heartbreak over a breakup. But when his ex drops a spare set of his keys at a local cafe, a waitress lets herself into his apartment and spruces up his life.
Title: L'uomo delle stelle | Rating: 6.8 | Overview: The adventures and deceptions of a photographer who travels through the small villages of Sicily pretending that he is working for the big film studios in Rome.
Title: Flirting with Disaster | Rating: 6.3 | Overview: Adopted as a child, new father Mel Colpin (Ben Stiller) decides he cannot name his son until he knows his birth parents, and determines to make a cross-country quest to find them. Accompanied by his wife, Nancy (Patricia Arquette), and an inept yet gorgeous adoption agent, Tina (Tea Leoni), he departs on an epic road trip that quickly devolves into a farce of mistaken identities, wrong turns, and overzealous and love-struck ATF agents (Josh Brolin, Richard Jenkins).
Title: The NeverEnding Story III | Rating: 4.4 | Overview: A young boy must restore order when a group of bullies steal the magical book that acts as a portal between Earth and the imaginary world of Fantasia.
Title: Jupiter's Wife | Rating: 0 | Overview: Michel Negroponte, a documentary filmmaker, meets Maggie one day in Central Park. Maggie claims to be married to the god Jupiter and the daughter of actor Robert Ryan. Michel gets to know Maggie over the next couple of years, and attempts to use her often outlandish stories as clues to reconstruct her past.
 - Written by James Meek"
Title: Pie in the Sky | Rating: 7 | Overview: Pie in the Sky is a 1996 American romantic comedy film about a young man obsessed with traffic gridlock who falls in love with an avant-garde dancer.
Title: Angela | Rating: 5.6 | Overview: A ten year old girl named Angela leads her six year old sister, Ellie, through various regimens of 'purification' in an attempt to rid themselves of their evil, which she believes to be the cause of their mother's mental illness. Precocious, to say the least, Angela has visions of Lucifer coming to take her and her sister away, and one of her remedies for this is for them to remain within a circle of their dolls and toys until they see a vision of the virgin Mary come to them. But such thinking can only lead to an ending befitting of her own mental state.
Title: Frankie Starlight | Rating: 5.4 | Overview: The quirky story of a young boy's adventures growing up with his stunningly beautiful mother and the two very different men who love her.
Title: Jade | Rating: 5.1 | Overview: Someone does a nasty hatchet job on a San Fransisco big noise and the Assistant D.A. takes charge of the investigation. Through a web of blackmail and prostitution involving the Governor, an old lover of the law man emerges as a prime suspect and he has to deal with his personal feelings as well as the case.
Title: Nueba Yol | Rating: 5.5 | Overview: Balbuena is a genial illegal immigrant who makes his way to New York City to take a bite out of the Big Apple. But his hopes of finding a better life soon begin to fade as Balbuena encounters one obstacle after another in the hardscrabble, uncaring metropolis.
Title: Sonic Outlaws | Rating: 0 | Overview: Within days after the release of Negativland's clever parody of U2 and Casey Kasem, recording industry giant Island Records descended upon the band with a battery of lawyers intent on erasing the piece from the history of rock music.  Craig "Tribulation 99" Baldwin follows this and other intellectual property controversies across the contemporary arts scene. Playful and ironic, his cut-and-paste collage-essay surveys the prospects for an "electronic folk culture" in the midst of an increasingly commodified corporate media landscape.
Title: Down Periscope | Rating: 5.6 | Overview: Bumbling Navy lieutenant Tom Dodge has been given one last chance to clean up his record. But Admiral Graham, his nemesis, assigns Dodge to the Stingray, a submarine that can barely keep afloat. To add insult to injury, the Stingray is to be the enemy flagship in the upcoming war games … and to make matters even worse, Dodge's crew is a band of idiots even more incompetent that he is!
Title: From the Journals of Jean Seberg | Rating: 6.5 | Overview: Mark Rappaport's creative bio-pic about actress Jean Seberg is presented in a first-person, autobiographical format (with Seberg played by Mary Beth Hurt). He seamlessly interweaves cinema, politics, American society and culture, and film theory to inform, entertain, and move the viewer. Seberg's many marriages, as well as her film roles, are discussed extensively. Her involvement with the Black Panther Movement and subsequent investigation by the FBI is covered. Notably, details of French New Wave cinema, Russian Expressionist (silent) films, and the careers of Jane Fonda, Vanessa Redgrave, and Clint Eastwood are also intensively examined. Much of the film is based on conjecture, but Rappaport encourages viewers to re-examine their ideas about women in film with this thought-provoking picture.
Title: Man of the Year | Rating: 3.8 | Overview: First-time director Dirk Shafer also penned this raucous "mockumentary," a blend of fact and fiction that re-creates his 1992 reign as Playgirl magazine's Centerfold of the Year. When Shafer chooses to keep the fact that he's gay a secret from the magazine's editors, he finds himself living the ultimate lie -- and incapable of giving female readers what they really want. Will he succumb to his lover's pressures to come out of the closet?
Title: The Neon Bible | Rating: 7.2 | Overview: While on a train, a teenage boy thinks about his life and the flamboyant aunt whose friendship acted as an emotional shield from his troubled family. This film evokes the haunting quality of memory while creating a heartfelt portrait of a boy's life in a rural 1940s Southern town.
Title: Target | Rating: 0 | Overview: A subtle yet violent commentary on feudal lords.
Title: Up Close & Personal | Rating: 5.9 | Overview: Tally Atwater has a dream: to be a prime-time network newscaster. She pursues this dream with nothing but ambition, raw talent and a homemade demo tape. Warren Justice is a brilliant, hard edged, veteran newsman. He sees Tally has talent and becomes her mentor. Tally’s career takes a meteoric rise and she and Warren fall in love. The romance that results is as intense and revealing as television news itself. Yet, each breaking story, every videotaped crisis that brings them together, also threatens to drive them apart...
Title: The Birdcage | Rating: 6.7 | Overview: A gay cabaret owner and his drag queen companion agree to put up a false straight front so that their son can introduce them to his fiancé's right-wing moralistic parents.
Title: Gospa | Rating: 7 | Overview: In 1981 in Medjugorje (BA), a group of kids claim that Virgin Mary appeared to them on a hill. The local priest believes them and spreads the word. Religious tourism blossoms. The communist government is concerned and arrests the priest.
Title: The Brothers McMullen | Rating: 6.3 | Overview: Deals with the lives of the three Irish Catholic McMullen brothers from Long Island, New York, over three months, as they grapple with basic ideas and values — love, sex, marriage, religion and family — in the 1990s. Directed, written, produced by and starring Edward Burns.
Title: Bad Boys | Rating: 6.5 | Overview: Marcus Burnett is a hen-pecked family man. Mike Lowry is a foot-loose and fancy free ladies' man. Both are Miami policemen, and both have 72 hours to reclaim a consignment of drugs stolen from under their station's nose. To complicate matters, in order to get the assistance of the sole witness to a murder, they have to pretend to be each other.
Title: The Amazing Panda Adventure | Rating: 5 | Overview: Far from home in the lush bamboo forests of China, ten-year-old Ryan Tyler, with the help of a young girl, goes on a wonderful journey to rescue a baby panda taken by poachers.
Title: The Basketball Diaries | Rating: 7.2 | Overview: Film adaptation of street tough Jim Carroll's epistle about his kaleidoscopic free fall into the harrowing world of drug addiction.
Title: An Awfully Big Adventure | Rating: 6 | Overview: An Awfully Big Adventure is a 1995 drama film about a theatre company in Liverpool, set in 1947 and based on the 1989 novel of the same name by Beryl Bainbridge.
Title: Amateur | Rating: 6.5 | Overview: A man wakes up in an alley, bleeding and with no memory of who he is. He stumbles into a coffee shop and is befriended by a charitable ex-nun who is failing in her attempts to write marketable pornography.
Title: Apollo 13 | Rating: 7.3 | Overview: The true story of technical troubles that scuttle the Apollo 13 lunar mission in 1971, risking the lives of astronaut Jim Lovell and his crew, with the failed journey turning into a thrilling saga of heroism. Drifting more than 200,000 miles from Earth, the astronauts work furiously with the ground crew to avert tragedy.
Title: Rob Roy | Rating: 6.5 | Overview: In the highlands of Scotland in the 1700s, Rob Roy tries to lead his small town to a better future, by borrowing money from the local nobility to buy cattle to herd to market. When the money is stolen, Rob is forced into a Robin Hood lifestyle to defend his family and honour.
Title: The Addiction | Rating: 6.4 | Overview: A vampiric doctoral student tries to follow the philosophy of a nocturnal comrade and control her thirst for blood.
Title: Batman Forever | Rating: 5.2 | Overview: The Dark Knight of Gotham City confronts a dastardly duo: Two-Face and the Riddler. Formerly District Attorney Harvey Dent, Two-Face believes Batman caused the courtroom accident which left him disfigured on one side. And Edward Nygma, computer-genius and former employee of millionaire Bruce Wayne, is out to get the philanthropist; as The Riddler. Former circus acrobat Dick Grayson, his family killed by Two-Face, becomes Wayne's ward and Batman's new partner Robin.
Title: Belle de jour | Rating: 7.3 | Overview: Beautiful young housewife Séverine Serizy cannot reconcile her masochistic fantasies with her everyday life alongside dutiful husband Pierre. When her lovestruck friend Henri mentions a secretive high-class brothel run by Madame Anais, Séverine begins to work there during the day under the name Belle de Jour. But when one of her clients grows possessive, she must try to go back to her normal life.
Title: Beyond Rangoon | Rating: 6.4 | Overview: Patricia Arquette stars as American widow Laura Bowman, a young doctor who's unwittingly drawn into political turmoil while vacationing in Burma in the late 1980s, in this fictionalized drama based on actual events. Bowman initially left San Francisco with her sister (Frances McDormand) in an attempt to escape painful memories of her husband and son's violent deaths. But her fight to escape to Thailand could prove just as harrowing.
Title: Blue in the Face | Rating: 6.8 | Overview: Auggie runs a small tobacco shop in Brooklyn, New York. The whole neighborhood comes to visit him to buy cigarettes and have some small talk. During the movie Lou Reed tries to explain why he has to have a cut on his health insurance bill if he keeps smoking and Madonna acts as a Singing Telegram.
Title: Canadian Bacon | Rating: 5.9 | Overview: Canadian Bacon is the only fictitious film from Director Michael Moore. This comedy is about an American president who decides to go to war to bring the public’s opinion of him up during election time. Canadian Bacon is actor John Candy’s last film.
Title: Casper | Rating: 6 | Overview: Furious that her late father only willed her his gloomy-looking mansion rather than his millions, Carrigan Crittenden is ready to burn the place to the ground when she discovers a map to a treasure hidden in the house. But when she enters the rickety mansion to seek her claim, she is frightened away by a wicked wave of ghosts. Determined to get her hands on this hidden fortune, she hires afterlife therapist Dr. James Harvey to exorcise the ghosts from the mansion. Harvey and his daughter Kat move in, and soon Kat meets Casper, the ghost of a young boy who's "the friendliest ghost you know." But not so friendly are Casper's uncles--Stretch, Fatso and Stinkie--who are determined to drive all "fleshies" away.
Title: Clockers | Rating: 6.8 | Overview: Strike is a young city drug pusher under the tutelage of drug-lord Rodney Little.When a night man at a fast-food restaurant is found with four bullets in his body, Strike's older brother turns himself in as the killer. Det. Rocco Klein doesn't buy the story, however, and sets out to find the truth, and it seems that all the fingers point toward Strike &amp; Rodney.
Title: Congo | Rating: 5 | Overview: Eight people embark on an expedition into the Congo, a mysterious expanse of unexplored Africa where human greed and the laws of nature have gone berserk. When the thrill-seekers -- some with ulterior motives -- stumble across a race of killer apes.
Title: Crimson Tide | Rating: 7 | Overview: On a US nuclear missile sub, a young first officer stages a mutiny to prevent his trigger happy captain from launching his missiles before confirming his orders to do so.
Title: Crumb | Rating: 7.6 | Overview: This movie chronicles the life and times of R. Crumb. Robert Crumb is the cartoonist/artist who drew Keep On Truckin', Fritz the Cat, and played a major pioneering role in the genesis of underground comix. Through interviews with his mother, two brothers, wife, and ex-girlfriends, as well as selections from his vast quantity of graphic art, we are treated to a darkly comic ride through one man's subconscious mind.
Title: Desperado | Rating: 6.8 | Overview: A gunslinger is embroiled in a war with a local drug runner.
Title: Devil in a Blue Dress | Rating: 6.3 | Overview: In late 1940s Los Angeles, Easy Rawlins is an unemployed black World War II veteran with few job prospects. At a bar, Easy meets DeWitt Albright, a mysterious white man looking for someone to investigate the disappearance of a missing white woman named Daphne Monet, who he suspects is hiding out in one of the city's black jazz clubs. Strapped for money and facing house payments, Easy takes the job, but soon finds himself in over his head.
Title: Die Hard: With a Vengeance | Rating: 6.9 | Overview: New York detective John McClane is back and kicking bad-guy butt in the third installment of this action-packed series, which finds him teaming with civilian Zeus Carver to prevent the loss of innocent lives. McClane thought he'd seen it all, until a genius named Simon engages McClane, his new "partner" -- and his beloved city -- in a deadly game that demands their concentration.
Title: The Doom Generation | Rating: 5.6 | Overview: Jordan White and Amy Blue, two troubled teens, pick up an adolescent drifter, Xavier Red. Together, the threesome embark on a sex and violence-filled journey through an America of psychos and quickiemarts.
Title: Feast of July | Rating: 0 | Overview: After an abandoned young woman in late 19th Century England is taken in by a rural couple with three handsome sons, tragic consequences result.
Title: First Knight | Rating: 5.9 | Overview: The timeless tale of King Arthur and the legend of Camelot are retold in this passionate period drama. Arthur is reluctant to hand the crown to Lancelot, and Guinevere is torn between her loyalty to her husband and her growing love for his rival. But Lancelot must balance his loyalty to the throne with the rewards of true love.
Title: Free Willy 2 - The Adventure Home | Rating: 5.5 | Overview: Jesse becomes reunited with Willy three years after the whale's jump to freedom as the teenager tries to rescue the killer whale and other orcas from an oil spill.
Title: Hackers | Rating: 6.2 | Overview: Along with his new friends, a teenager who was arrested by the US Secret Service and banned from using a computer for writing a computer virus discovers a plot by a nefarious hacker, but they must use their computer skills to find the evidence while being pursued by the Secret Service and the evil computer genius behind the virus.
Title: Jeffrey | Rating: 6.5 | Overview: Jeffery, a young gay man in New York, decides that sex is too much and decided to become celibate. He immediately meets the man of his dreams and must decide whether or not love is worth the danger of a boyfriend dying.
Title: Johnny Mnemonic | Rating: 5.5 | Overview: A data courier, literally carrying a data package inside his head, must deliver it before he dies from the burden or is killed by the Yakuza.  In a dystopian 2021, Johnny (Keanu Reeves) is a data trafficker who has an implant that allows him to securely store data too sensitive for regular computer networks. On one delivery run, he accepts a package that not only exceeds the implant's safety limits - and will kill him if the data is not removed in time - but also contains information far more important and valuable than he had ever imagined. On a race against time, he must avoid the assassins sent to kill him and remove the data before it, too, ends his life.
Title: Judge Dredd | Rating: 5.4 | Overview: In a dystopian future, Dredd, the most famous judge (a cop with instant field judiciary powers) is convicted for a crime he did not commit while his murderous counterpart escapes.
Title: Jury Duty | Rating: 4 | Overview: When jobless Tommy Collins discovers that sequestered jurors earn free room and board as well as $5-a-day, he gets himself assigned to a jury in a murder trial. Once there, he does everything he can to prolong the trial and deliberations and make the sequestration more comfortable for himself.
Title: Kids | Rating: 6.8 | Overview: A controversial portrayal of teens in New York City which exposes a deeply disturbing world of sex and substance abuse. The film focuses on a sexually reckless, freckle-faced boy named Telly, whose goal is to have sex with as many different girls as he can. When Jenny, a girl who has had sex only once, tests positive for HIV, she knows she contracted the disease from Telly. When Jenny discovers that Telly's idea of "safe sex" is to only have sex with virgins, and is continuing to pass the disease onto other unsuspecting girls, Jenny makes it her business to try to stop him.
Title: Living in Oblivion | Rating: 7.2 | Overview: Film about filmmaking. It takes place during one day on set of non-budget movie. Ultimate tribute to all independent filmmakers.
Title: Lord of Illusions | Rating: 5.9 | Overview: During a routine case in L.A., NY private investigator Harry D'Amour stumbles over members of a fanatic cult who are preparing for the resurrection of their leader Nix, a powerful magician who was killed 13 years earlier.
Title: Love & Human Remains | Rating: 7 | Overview: Dreary urban landscape of an anonymous Canadian city. Dark comedy about a group of twentysomethings looking for love and meaning in the '90s. The film focuses on roommates David, a gay waiter who has has given up on his acting career, and Candy, a book reviewer who is also David's ex-lover. David and Candy's lives are entangled with those of David's friends and Candy's dates.
Title: Mad Love | Rating: 5.5 | Overview: Matt falls for Casey, the new girl in school. She's fun-loving and eccentric, but there's a darkness to her whimsy that Matt can't begin to comprehend. When Casey attempts to commit suicide, her parents place her in a mental institution. Matt springs her out, and together the young lovers head on a road trip. They believe their love can "cure" Casey's problems. Matt starts to wonder, though, if are they inspired or misguided.
Title: Mallrats | Rating: 6.8 | Overview: Both dumped by their girlfriends, two best friends seek refuge in the local mall.
Title: Mighty Morphin Power Rangers: The Movie | Rating: 5.2 | Overview: Power up with six incredible teens who out-maneuver and defeat evil everywhere as the Mighty Morphin Power Ranger, But this time the Power Rangers may have met their match, when they face off with the most sinister monster the galaxy has ever seen.
Title: Moonlight and Valentino | Rating: 5.6 | Overview: Four women who discover untapped strength within themselves when they finally let go of what divides them
Title: Mute Witness | Rating: 6.4 | Overview: Billy is mute, but it hasn't kept her from becoming a successful makeup artist. While in Russia, working on a film directed by her sister's boyfriend, Andy, Billy finds herself trapped in the studio one night and is horrified to see a snuff film being made. Billy escapes and, with the help of her sister, Kate, alerts authorities about what she saw. Unfortunately, in doing so, she makes an enemy of the Russian mafia, who funded the snuff film.
Title: Nadja | Rating: 5.9 | Overview: This ultra-hip, post-modern vampire tale is set in contemporary New York City. Members of a dysfunctional family of vampires are trying to come to terms with each other, in the wake of their father's death. Meanwhile, they are being hunted by Dr. Van Helsing and his hapless nephew. As in all good vampire movies, forces of love are pitted against forces of destruction.
Title: The Net | Rating: 5.6 | Overview: Angela Bennett is a freelance software engineer who lives in a world of computer technology. When a cyber friend asks Bennett to debug a new game, she inadvertently becomes involved in a conspiracy that will soon turn her life upside down. While on vacation in Mexico, her purse is stolen. She soon finds that people and events may not be what they seem as she becomes the target of an assassination. Her vacation is ruined.  She gets a new passport at the U.S. Embassy in Mexico but it has the wrong name, Ruth Marx. When she returns to the U.S. to sort things out, she discovers that Ruth Marx has an unsavory past and a lengthy  police record. To make matters worse, another person has assumed her real identity ...
Title: Nine Months | Rating: 5.5 | Overview: When he finds out his longtime girlfriend is pregnant, a commitment-phobe realizes he might have to change his lifestyle for better or much, much worse.
Title: Party Girl | Rating: 5.8 | Overview: Although Mary has little income, she still finds ways to spend her nights at clubs. After being arrested for throwing an illegal rave, she asks her aunt Judy for bail money. Judy then finds Mary a job at her library so that Mary can repay her. Initially, Mary finds the job as a clerk boring and stifling, and prefers to get to know a street food vendor whom she likes. However, Mary must refocus her life once she loses her job and apartment.
Title: The Prophecy | Rating: 6.4 | Overview: The angel Gabriel comes to Earth to collect a soul which will end the stalemated war in Heaven, and only a former priest and a little girl can stop him.
Title: Reckless | Rating: 10 | Overview: On Christmas eve, a relentlessly cheerful woman escapes from the killers hired by her husband, and embarks on a series of strange encounters.
Title: Safe | Rating: 7.2 | Overview: Carol, a typical upper middle-class housewife, begins to complain of vague symptoms of illness. She "doesn't feel right," has unexplained headaches, congestion, a dry cough, nosebleeds, vomiting, and trouble breathing. Her family doctor treats her concerns dismissively and suggests a psychiatrist. Eventually, an allergist tells her that she has Environmental Illness.
Title: The Scarlet Letter | Rating: 5.5 | Overview: Set in puritanical Boston in the mid 1600s, the story of seamstress Hester Prynne, who is outcast after she becomes pregnant by a respected reverend. She refuses to divulge the name of the father, is "convicted" of adultery and forced to wear a scarlet "A" until an Indian attack unites the Puritans and leads to a reevaluation of their laws and morals.
Title: The Show | Rating: 5.3 | Overview: A documentary about the culture of hip-hop. Through interviews with some of hip-hops biggest names, the film makers attempt to find out why it has become so popular.
Title: Showgirls | Rating: 4.9 | Overview: A young drifter named Nomi arrives in Las Vegas to become a dancer and soon sets about clawing and pushing her way to become a top showgirl.
Title: Smoke | Rating: 7.2 | Overview: Writer Paul Benjamin is nearly hit by a bus when he leaves Auggie Wren's smoke shop. Stranger Rashid Cole  saves his life, and soon middle-aged Paul tells homeless Rashid that he wouldn't mind a short-term housemate. Still grieving over his wife's murder, Paul is moved by both Rashid's quest to reconnect with his father and Auggie's discovery that a woman who might be his daughter is about to give birth.
Title: Something to Talk About | Rating: 5.7 | Overview: In one of her best-ever roles, Julia Roberts is Grace, whose reaction to the infidelities of Eddie (Dennis Quaid) turns the lives and loves of the people around her into something like falling dominoes. Robert Duvall, Gena Rowlands, Kyra Sedgwick and others in "the year's best ensemble of characters" (Jack Matthews, 'Newsday') co-star in this juicy, truthful story written by Callie Khouri
Title: Species | Rating: 5.5 | Overview: In 1993, the Search for Extra Terrestrial Intelligence Project receives a transmission detailing an alien DNA structure, along with instructions on how to splice it with human DNA. The result is Sil, a sensual but deadly creature who can change from a beautiful woman to an armour-plated killing machine in the blink of an eye.
Title: The Stars Fell on Henrietta | Rating: 6.6 | Overview: The setting is early America during the oil boom. An elderly, down on his luck 'oil man', Mr. Cox finds himself in the town of Henrietta. Using unconventional methods, he convinces himself and local Don Day that there is oil on Day's land. The financially strapped Day puts everything into finding oil...but at what cost?
Title: Strange Days | Rating: 6.8 | Overview: Set in the year 1999 during the last days of the old millennium, the movie tells the story of Lenny Nero, an ex-cop who now deals with data-discs containing recorded memories and emotions. One day he receives a disc which contains the memories of a murderer killing a prostitute. Lenny investigates and is pulled deeper and deeper in a whirl of blackmail, murder and rape. Will he survive and solve the case?
Title: Les parapluies de Cherbourg | Rating: 7.6 | Overview: This simple romantic tragedy begins in 1957. Guy Foucher, a 20-year-old French auto mechanic, has fallen in love with 17-year-old Geneviève Emery, an employee in her widowed mother's chic but financially embattled umbrella shop. On the evening before Guy is to leave for a two-year tour of combat in Algeria, he and Geneviève make love. She becomes pregnant and must choose between waiting for Guy's return or accepting an offer of marriage from a wealthy diamond merchant.
Title: The Tie That Binds | Rating: 4.6 | Overview: John Netherwood and his wife Leann are fugitives who are both wanted for murder. They have a young daughter named Janie and they want her back.
Title: Three Wishes | Rating: 6.1 | Overview: While Jane Holman (Mastrantonio) is driving with her two sons, she accidentally runs into a drifter, Jack McCloud (Swayze), who breaks his leg. Being responsible,  Jane invites Jack, and his dog, to stay at her home until his leg has healed.  Jack struggles to adapt their lifestyle, and finds himself loved by the family. He starts teaching baseball to Tom, who misses his father, who was lost in the Korean war. Jack and Tom develop a strong bond of friendship. Meanwhile, Gunny believes that there is more to Jack and Betty Jane than meets the eye...  We learn that Jack, is Jack McCloud, a Star White Socks baseball player in 1941, who dropped out of the league, after his first season, and; "was never heard from again" ...  A wonderful story.  We witness magic between a boy's imagination, and Jack's dog, and are never sure if we are witnessing imagination or magic by the dog.  A story of friendship, family, and learning that life isn't always as cut and dried as we often believe.
"""

# 4. Create the Frontend Input UI Elements
user_query = st.text_input(
    label="Describe the precise vibe, theme, or plot style you want:",
    placeholder="e.g., A mind-bending space exploration movie that deals with family relationships..."
)

# 5. Add a submit button to trigger the AI backend processing loop
if st.button("Generate Recommendations"):
    if user_query.strip() == "":
        st.warning("Please type a mood or theme first!")
    else:
        with st.spinner("Analyzing the database to match your vibe and searching for results..."):
            try:
                response = client.models.generate_content(
                    model="gemini-3.5-flash",
                    contents=user_query,
                    config={'system_instruction': SYSTEM_INSTRUCTION}
                )
                st.success("Here are your personalized matches:")
                st.markdown(response.text)
                
            except Exception as e:
                st.error(f"An error occurred: {e}")